// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecuteAction.proto

package de.tum.in.i22.uc.pdp.internal.gproto;

public final class ExecuteActionProto {
  private ExecuteActionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PbExecuteActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    java.util.List<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter> 
        getParameterList();
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter getParameter(int index);
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    int getParameterCount();
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    java.util.List<? extends de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder> 
        getParameterOrBuilderList();
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder getParameterOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code de.tum.in.i22.cm.pdp.PbExecuteAction}
   */
  public static final class PbExecuteAction extends
      com.google.protobuf.GeneratedMessage
      implements PbExecuteActionOrBuilder {
    // Use PbExecuteAction.newBuilder() to construct.
    private PbExecuteAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PbExecuteAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PbExecuteAction defaultInstance;
    public static PbExecuteAction getDefaultInstance() {
      return defaultInstance;
    }

    public PbExecuteAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PbExecuteAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                parameter_ = new java.util.ArrayList<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter>();
                mutable_bitField0_ |= 0x00000002;
              }
              parameter_.add(input.readMessage(de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          parameter_ = java.util.Collections.unmodifiableList(parameter_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction.class, de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction.Builder.class);
    }

    public static com.google.protobuf.Parser<PbExecuteAction> PARSER =
        new com.google.protobuf.AbstractParser<PbExecuteAction>() {
      public PbExecuteAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbExecuteAction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PbExecuteAction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;
    public static final int PARAMETER_FIELD_NUMBER = 2;
    private java.util.List<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter> parameter_;
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    public java.util.List<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter> getParameterList() {
      return parameter_;
    }
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    public java.util.List<? extends de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder> 
        getParameterOrBuilderList() {
      return parameter_;
    }
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    public int getParameterCount() {
      return parameter_.size();
    }
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter getParameter(int index) {
      return parameter_.get(index);
    }
    /**
     * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
     */
    public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder getParameterOrBuilder(
        int index) {
      return parameter_.get(index);
    }

    private void initFields() {
      name_ = "";
      parameter_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getParameterCount(); i++) {
        if (!getParameter(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < parameter_.size(); i++) {
        output.writeMessage(2, parameter_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < parameter_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, parameter_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.tum.in.i22.cm.pdp.PbExecuteAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction.class, de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction.Builder.class);
      }

      // Construct using de.tum.in.i22.cm.pdp.gproto.ExecuteActionProto.PbExecuteAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParameterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (parameterBuilder_ == null) {
          parameter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          parameterBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_descriptor;
      }

      public de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction getDefaultInstanceForType() {
        return de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction.getDefaultInstance();
      }

      public de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction build() {
        de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction buildPartial() {
        de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction result = new de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (parameterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            parameter_ = java.util.Collections.unmodifiableList(parameter_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.parameter_ = parameter_;
        } else {
          result.parameter_ = parameterBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction) {
          return mergeFrom((de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction other) {
        if (other == de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (parameterBuilder_ == null) {
          if (!other.parameter_.isEmpty()) {
            if (parameter_.isEmpty()) {
              parameter_ = other.parameter_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParameterIsMutable();
              parameter_.addAll(other.parameter_);
            }
            onChanged();
          }
        } else {
          if (!other.parameter_.isEmpty()) {
            if (parameterBuilder_.isEmpty()) {
              parameterBuilder_.dispose();
              parameterBuilder_ = null;
              parameter_ = other.parameter_;
              bitField0_ = (bitField0_ & ~0x00000002);
              parameterBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParameterFieldBuilder() : null;
            } else {
              parameterBuilder_.addAllMessages(other.parameter_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getParameterCount(); i++) {
          if (!getParameter(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.tum.in.i22.uc.pdp.internal.gproto.ExecuteActionProto.PbExecuteAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;
      private java.util.List<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter> parameter_ =
        java.util.Collections.emptyList();
      private void ensureParameterIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          parameter_ = new java.util.ArrayList<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter>(parameter_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder> parameterBuilder_;

      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public java.util.List<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter> getParameterList() {
        if (parameterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parameter_);
        } else {
          return parameterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public int getParameterCount() {
        if (parameterBuilder_ == null) {
          return parameter_.size();
        } else {
          return parameterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter getParameter(int index) {
        if (parameterBuilder_ == null) {
          return parameter_.get(index);
        } else {
          return parameterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder setParameter(
          int index, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter value) {
        if (parameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParameterIsMutable();
          parameter_.set(index, value);
          onChanged();
        } else {
          parameterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder setParameter(
          int index, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder builderForValue) {
        if (parameterBuilder_ == null) {
          ensureParameterIsMutable();
          parameter_.set(index, builderForValue.build());
          onChanged();
        } else {
          parameterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder addParameter(de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter value) {
        if (parameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParameterIsMutable();
          parameter_.add(value);
          onChanged();
        } else {
          parameterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder addParameter(
          int index, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter value) {
        if (parameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParameterIsMutable();
          parameter_.add(index, value);
          onChanged();
        } else {
          parameterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder addParameter(
          de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder builderForValue) {
        if (parameterBuilder_ == null) {
          ensureParameterIsMutable();
          parameter_.add(builderForValue.build());
          onChanged();
        } else {
          parameterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder addParameter(
          int index, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder builderForValue) {
        if (parameterBuilder_ == null) {
          ensureParameterIsMutable();
          parameter_.add(index, builderForValue.build());
          onChanged();
        } else {
          parameterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder addAllParameter(
          java.lang.Iterable<? extends de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter> values) {
        if (parameterBuilder_ == null) {
          ensureParameterIsMutable();
          super.addAll(values, parameter_);
          onChanged();
        } else {
          parameterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder clearParameter() {
        if (parameterBuilder_ == null) {
          parameter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          parameterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public Builder removeParameter(int index) {
        if (parameterBuilder_ == null) {
          ensureParameterIsMutable();
          parameter_.remove(index);
          onChanged();
        } else {
          parameterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder getParameterBuilder(
          int index) {
        return getParameterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder getParameterOrBuilder(
          int index) {
        if (parameterBuilder_ == null) {
          return parameter_.get(index);  } else {
          return parameterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public java.util.List<? extends de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder> 
           getParameterOrBuilderList() {
        if (parameterBuilder_ != null) {
          return parameterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parameter_);
        }
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder addParameterBuilder() {
        return getParameterFieldBuilder().addBuilder(
            de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder addParameterBuilder(
          int index) {
        return getParameterFieldBuilder().addBuilder(
            index, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .de.tum.in.i22.cm.pdp.PbParameter parameter = 2;</code>
       */
      public java.util.List<de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder> 
           getParameterBuilderList() {
        return getParameterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder> 
          getParameterFieldBuilder() {
        if (parameterBuilder_ == null) {
          parameterBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameter.Builder, de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.PbParameterOrBuilder>(
                  parameter_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          parameter_ = null;
        }
        return parameterBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:de.tum.in.i22.cm.pdp.PbExecuteAction)
    }

    static {
      defaultInstance = new PbExecuteAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:de.tum.in.i22.cm.pdp.PbExecuteAction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ExecuteAction.proto\022\024de.tum.in.i22.cm." +
      "pdp\032\017Parameter.proto\"U\n\017PbExecuteAction\022" +
      "\014\n\004name\030\001 \002(\t\0224\n\tparameter\030\002 \003(\0132!.de.tu" +
      "m.in.i22.cm.pdp.PbParameterB1\n\033de.tum.in" +
      ".i22.cm.pdp.gprotoB\022ExecuteActionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_tum_in_i22_cm_pdp_PbExecuteAction_descriptor,
              new java.lang.String[] { "Name", "Parameter", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.tum.in.i22.uc.pdp.internal.gproto.ParameterProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
