# components/pdp/pdpInterfaces/SConscript
import os, sys
Import('env','curBaseDir')

pdpCCFlags=env['CCFLAGS'] + " -DLIBXML_STATIC "
if env['PEFCONFIG']['pdpjni'] == True:
  pdpCCFlags=pdpCCFlags + " -DPDP_JNI "
  pdpJNIobject=env.rdObject('pdpInJNI.c', ccflags = env['CCFLAGS']+pdpCCFlags)
  env.rdAlias('pdpInterfaces', pdpJNIobject)

if env['PDPCONFIG']['PDP_TCPSOCKET']!=0:
  pdpSocketObject=env.rdObject('pdpInSocket.c', ccflags = env['CCFLAGS']+pdpCCFlags)
  env.rdAlias('pdpInterfaces', pdpSocketObject)

pdpInterfacesObject=env.rdObject('pdpCommInterfaces.c', ccflags = env['CCFLAGS']+pdpCCFlags)
env.rdAlias('pdpInterfaces', pdpInterfacesObject)

pdpPEPObject=env.rdObject('pdpOutPEP.c', ccflags = env['CCFLAGS']+pdpCCFlags)
env.rdAlias('pdpInterfaces', pdpPEPObject)

pdpPXPObject=env.rdObject('pdpOutPXP.c', ccflags = env['CCFLAGS']+pdpCCFlags)
env.rdAlias('pdpInterfaces', pdpPXPObject)

pdpPIPObject=env.rdObject('pdpOutPIP.c', ccflags = env['CCFLAGS']+pdpCCFlags)
env.rdAlias('pdpInterfaces', pdpPIPObject)





