// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PdpProtos.proto

package de.tum.in.i22.pdp.gpb;

// Suppress warning added manually by Stoimenov
@SuppressWarnings(value = { "all" })
public final class PdpProtos {
  private PdpProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GpEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .pdp.GpEvent.MapEntry mapEntry = 2;
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    java.util.List<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry> 
        getMapEntryList();
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry getMapEntry(int index);
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    int getMapEntryCount();
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    java.util.List<? extends de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder> 
        getMapEntryOrBuilderList();
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder getMapEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pdp.GpEvent}
   */
  public static final class GpEvent extends
      com.google.protobuf.GeneratedMessage
      implements GpEventOrBuilder {
    // Use GpEvent.newBuilder() to construct.
    private GpEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GpEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GpEvent defaultInstance;
    public static GpEvent getDefaultInstance() {
      return defaultInstance;
    }

    public GpEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GpEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                mapEntry_ = new java.util.ArrayList<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry>();
                mutable_bitField0_ |= 0x00000002;
              }
              mapEntry_.add(input.readMessage(de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          mapEntry_ = java.util.Collections.unmodifiableList(mapEntry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.class, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<GpEvent> PARSER =
        new com.google.protobuf.AbstractParser<GpEvent>() {
      public GpEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GpEvent> getParserForType() {
      return PARSER;
    }

    public interface MapEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string key = 1;
      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // optional string value = 2;
      /**
       * <code>optional string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>optional string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code pdp.GpEvent.MapEntry}
     */
    public static final class MapEntry extends
        com.google.protobuf.GeneratedMessage
        implements MapEntryOrBuilder {
      // Use MapEntry.newBuilder() to construct.
      private MapEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MapEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MapEntry defaultInstance;
      public static MapEntry getDefaultInstance() {
        return defaultInstance;
      }

      public MapEntry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MapEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_MapEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_MapEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.class, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder.class);
      }

      public static com.google.protobuf.Parser<MapEntry> PARSER =
          new com.google.protobuf.AbstractParser<MapEntry>() {
        public MapEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MapEntry(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MapEntry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pdp.GpEvent.MapEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_MapEntry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_MapEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.class, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder.class);
        }

        // Construct using de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_MapEntry_descriptor;
        }

        public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry getDefaultInstanceForType() {
          return de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.getDefaultInstance();
        }

        public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry build() {
          de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry buildPartial() {
          de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry result = new de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry) {
            return mergeFrom((de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry other) {
          if (other == de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // optional string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>optional string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:pdp.GpEvent.MapEntry)
      }

      static {
        defaultInstance = new MapEntry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:pdp.GpEvent.MapEntry)
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .pdp.GpEvent.MapEntry mapEntry = 2;
    public static final int MAPENTRY_FIELD_NUMBER = 2;
    private java.util.List<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry> mapEntry_;
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    public java.util.List<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry> getMapEntryList() {
      return mapEntry_;
    }
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    public java.util.List<? extends de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder> 
        getMapEntryOrBuilderList() {
      return mapEntry_;
    }
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    public int getMapEntryCount() {
      return mapEntry_.size();
    }
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry getMapEntry(int index) {
      return mapEntry_.get(index);
    }
    /**
     * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
     */
    public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder getMapEntryOrBuilder(
        int index) {
      return mapEntry_.get(index);
    }

    private void initFields() {
      name_ = "";
      mapEntry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMapEntryCount(); i++) {
        if (!getMapEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < mapEntry_.size(); i++) {
        output.writeMessage(2, mapEntry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < mapEntry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, mapEntry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pdp.GpEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.tum.in.i22.pdp.gpb.PdpProtos.GpEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.class, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.Builder.class);
      }

      // Construct using de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (mapEntryBuilder_ == null) {
          mapEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          mapEntryBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpEvent_descriptor;
      }

      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent getDefaultInstanceForType() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.getDefaultInstance();
      }

      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent build() {
        de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent buildPartial() {
        de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent result = new de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (mapEntryBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            mapEntry_ = java.util.Collections.unmodifiableList(mapEntry_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.mapEntry_ = mapEntry_;
        } else {
          result.mapEntry_ = mapEntryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent) {
          return mergeFrom((de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent other) {
        if (other == de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (mapEntryBuilder_ == null) {
          if (!other.mapEntry_.isEmpty()) {
            if (mapEntry_.isEmpty()) {
              mapEntry_ = other.mapEntry_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMapEntryIsMutable();
              mapEntry_.addAll(other.mapEntry_);
            }
            onChanged();
          }
        } else {
          if (!other.mapEntry_.isEmpty()) {
            if (mapEntryBuilder_.isEmpty()) {
              mapEntryBuilder_.dispose();
              mapEntryBuilder_ = null;
              mapEntry_ = other.mapEntry_;
              bitField0_ = (bitField0_ & ~0x00000002);
              mapEntryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMapEntryFieldBuilder() : null;
            } else {
              mapEntryBuilder_.addAllMessages(other.mapEntry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMapEntryCount(); i++) {
          if (!getMapEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .pdp.GpEvent.MapEntry mapEntry = 2;
      private java.util.List<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry> mapEntry_ =
        java.util.Collections.emptyList();
      private void ensureMapEntryIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          mapEntry_ = new java.util.ArrayList<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry>(mapEntry_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder> mapEntryBuilder_;

      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public java.util.List<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry> getMapEntryList() {
        if (mapEntryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mapEntry_);
        } else {
          return mapEntryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public int getMapEntryCount() {
        if (mapEntryBuilder_ == null) {
          return mapEntry_.size();
        } else {
          return mapEntryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry getMapEntry(int index) {
        if (mapEntryBuilder_ == null) {
          return mapEntry_.get(index);
        } else {
          return mapEntryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder setMapEntry(
          int index, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry value) {
        if (mapEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapEntryIsMutable();
          mapEntry_.set(index, value);
          onChanged();
        } else {
          mapEntryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder setMapEntry(
          int index, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder builderForValue) {
        if (mapEntryBuilder_ == null) {
          ensureMapEntryIsMutable();
          mapEntry_.set(index, builderForValue.build());
          onChanged();
        } else {
          mapEntryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder addMapEntry(de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry value) {
        if (mapEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapEntryIsMutable();
          mapEntry_.add(value);
          onChanged();
        } else {
          mapEntryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder addMapEntry(
          int index, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry value) {
        if (mapEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapEntryIsMutable();
          mapEntry_.add(index, value);
          onChanged();
        } else {
          mapEntryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder addMapEntry(
          de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder builderForValue) {
        if (mapEntryBuilder_ == null) {
          ensureMapEntryIsMutable();
          mapEntry_.add(builderForValue.build());
          onChanged();
        } else {
          mapEntryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder addMapEntry(
          int index, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder builderForValue) {
        if (mapEntryBuilder_ == null) {
          ensureMapEntryIsMutable();
          mapEntry_.add(index, builderForValue.build());
          onChanged();
        } else {
          mapEntryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder addAllMapEntry(
          java.lang.Iterable<? extends de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry> values) {
        if (mapEntryBuilder_ == null) {
          ensureMapEntryIsMutable();
          super.addAll(values, mapEntry_);
          onChanged();
        } else {
          mapEntryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder clearMapEntry() {
        if (mapEntryBuilder_ == null) {
          mapEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          mapEntryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public Builder removeMapEntry(int index) {
        if (mapEntryBuilder_ == null) {
          ensureMapEntryIsMutable();
          mapEntry_.remove(index);
          onChanged();
        } else {
          mapEntryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder getMapEntryBuilder(
          int index) {
        return getMapEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder getMapEntryOrBuilder(
          int index) {
        if (mapEntryBuilder_ == null) {
          return mapEntry_.get(index);  } else {
          return mapEntryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public java.util.List<? extends de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder> 
           getMapEntryOrBuilderList() {
        if (mapEntryBuilder_ != null) {
          return mapEntryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mapEntry_);
        }
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder addMapEntryBuilder() {
        return getMapEntryFieldBuilder().addBuilder(
            de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder addMapEntryBuilder(
          int index) {
        return getMapEntryFieldBuilder().addBuilder(
            index, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .pdp.GpEvent.MapEntry mapEntry = 2;</code>
       */
      public java.util.List<de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder> 
           getMapEntryBuilderList() {
        return getMapEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder> 
          getMapEntryFieldBuilder() {
        if (mapEntryBuilder_ == null) {
          mapEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntry.Builder, de.tum.in.i22.pdp.gpb.PdpProtos.GpEvent.MapEntryOrBuilder>(
                  mapEntry_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          mapEntry_ = null;
        }
        return mapEntryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pdp.GpEvent)
    }

    static {
      defaultInstance = new GpEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pdp.GpEvent)
  }

  public interface GpStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .pdp.GpStatus.EStatus value = 1;
    /**
     * <code>required .pdp.GpStatus.EStatus value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>required .pdp.GpStatus.EStatus value = 1;</code>
     */
    de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus getValue();
  }
  /**
   * Protobuf type {@code pdp.GpStatus}
   */
  public static final class GpStatus extends
      com.google.protobuf.GeneratedMessage
      implements GpStatusOrBuilder {
    // Use GpStatus.newBuilder() to construct.
    private GpStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GpStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GpStatus defaultInstance;
    public static GpStatus getDefaultInstance() {
      return defaultInstance;
    }

    public GpStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GpStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus value = de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                value_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.class, de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<GpStatus> PARSER =
        new com.google.protobuf.AbstractParser<GpStatus>() {
      public GpStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GpStatus> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code pdp.GpStatus.EStatus}
     */
    public enum EStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR1 = 1;</code>
       */
      ERROR1(0, 1),
      /**
       * <code>OKAY = 2;</code>
       */
      OKAY(1, 2),
      /**
       * <code>ERROR2 = 3;</code>
       */
      ERROR2(2, 3),
      /**
       * <code>INIBIT = 4;</code>
       */
      INIBIT(3, 4),
      /**
       * <code>ALLOW = 5;</code>
       */
      ALLOW(4, 5),
      /**
       * <code>MODIFY = 6;</code>
       */
      MODIFY(5, 6),
      ;

      /**
       * <code>ERROR1 = 1;</code>
       */
      public static final int ERROR1_VALUE = 1;
      /**
       * <code>OKAY = 2;</code>
       */
      public static final int OKAY_VALUE = 2;
      /**
       * <code>ERROR2 = 3;</code>
       */
      public static final int ERROR2_VALUE = 3;
      /**
       * <code>INIBIT = 4;</code>
       */
      public static final int INIBIT_VALUE = 4;
      /**
       * <code>ALLOW = 5;</code>
       */
      public static final int ALLOW_VALUE = 5;
      /**
       * <code>MODIFY = 6;</code>
       */
      public static final int MODIFY_VALUE = 6;


      public final int getNumber() { return value; }

      public static EStatus valueOf(int value) {
        switch (value) {
          case 1: return ERROR1;
          case 2: return OKAY;
          case 3: return ERROR2;
          case 4: return INIBIT;
          case 5: return ALLOW;
          case 6: return MODIFY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EStatus>() {
              public EStatus findValueByNumber(int number) {
                return EStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final EStatus[] VALUES = values();

      public static EStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pdp.GpStatus.EStatus)
    }

    private int bitField0_;
    // required .pdp.GpStatus.EStatus value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus value_;
    /**
     * <code>required .pdp.GpStatus.EStatus value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .pdp.GpStatus.EStatus value = 1;</code>
     */
    public de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus getValue() {
      return value_;
    }

    private void initFields() {
      value_ = de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus.ERROR1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, value_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, value_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pdp.GpStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.tum.in.i22.pdp.gpb.PdpProtos.GpStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.class, de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.Builder.class);
      }

      // Construct using de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value_ = de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus.ERROR1;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.internal_static_pdp_GpStatus_descriptor;
      }

      public de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus getDefaultInstanceForType() {
        return de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.getDefaultInstance();
      }

      public de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus build() {
        de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus buildPartial() {
        de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus result = new de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus) {
          return mergeFrom((de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus other) {
        if (other == de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .pdp.GpStatus.EStatus value = 1;
      private de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus value_ = de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus.ERROR1;
      /**
       * <code>required .pdp.GpStatus.EStatus value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .pdp.GpStatus.EStatus value = 1;</code>
       */
      public de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus getValue() {
        return value_;
      }
      /**
       * <code>required .pdp.GpStatus.EStatus value = 1;</code>
       */
      public Builder setValue(de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .pdp.GpStatus.EStatus value = 1;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = de.tum.in.i22.pdp.gpb.PdpProtos.GpStatus.EStatus.ERROR1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pdp.GpStatus)
    }

    static {
      defaultInstance = new GpStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pdp.GpStatus)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pdp_GpEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pdp_GpEvent_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pdp_GpEvent_MapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pdp_GpEvent_MapEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pdp_GpStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pdp_GpStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PdpProtos.proto\022\003pdp\"h\n\007GpEvent\022\014\n\004nam" +
      "e\030\001 \001(\t\022\'\n\010mapEntry\030\002 \003(\0132\025.pdp.GpEvent." +
      "MapEntry\032&\n\010MapEntry\022\013\n\003key\030\001 \002(\t\022\r\n\005val" +
      "ue\030\002 \001(\t\"\200\001\n\010GpStatus\022$\n\005value\030\001 \002(\0162\025.p" +
      "dp.GpStatus.EStatus\"N\n\007EStatus\022\n\n\006ERROR1" +
      "\020\001\022\010\n\004OKAY\020\002\022\n\n\006ERROR2\020\003\022\n\n\006INIBIT\020\004\022\t\n\005" +
      "ALLOW\020\005\022\n\n\006MODIFY\020\006B\"\n\025de.tum.in.i22.pdp" +
      ".gpbB\tPdpProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pdp_GpEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pdp_GpEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pdp_GpEvent_descriptor,
              new java.lang.String[] { "Name", "MapEntry", });
          internal_static_pdp_GpEvent_MapEntry_descriptor =
            internal_static_pdp_GpEvent_descriptor.getNestedTypes().get(0);
          internal_static_pdp_GpEvent_MapEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pdp_GpEvent_MapEntry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_pdp_GpStatus_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pdp_GpStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pdp_GpStatus_descriptor,
              new java.lang.String[] { "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
