//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 09:57:23 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iese.fhg.de/pef/1.0/action", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tum.in.i22.pdp.xsd.action;
