//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:09:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iese.fhg.de/pef/1.0/enforcementLanguage", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tum.in.i22.uc.ecajaxb;
