//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:09:43 PM CEST 
//


package de.tum.in.i22.uc.ecajaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicySetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicySetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interfaceDescriptions" type="{http://www.iese.fhg.de/pef/1.0/enforcementLanguage}InterfaceDescriptionType" minOccurs="0"/>
 *         &lt;element name="actionDescriptions" type="{http://www.iese.fhg.de/pef/1.0/action}ActionDescriptionStoreType" minOccurs="0"/>
 *         &lt;element name="contextDescriptions" type="{http://www.iese.fhg.de/pef/1.0/context}ContextDescriptionType" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="detectiveMechanism" type="{http://www.iese.fhg.de/pef/1.0/enforcementLanguage}DetectiveMechanismType"/>
 *           &lt;element name="preventiveMechanism" type="{http://www.iese.fhg.de/pef/1.0/enforcementLanguage}PreventiveMechanismType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="policy")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "policy", propOrder = {
    "interfaceDescriptions",
    "actionDescriptions",
    "contextDescriptions",
    "detectiveMechanismOrPreventiveMechanism"
})
public class PolicySetType {

    protected InterfaceDescriptionType interfaceDescriptions;
    protected ActionDescriptionStoreType actionDescriptions;
    protected ContextDescriptionType contextDescriptions;
    @XmlElements({
        @XmlElement(name = "detectiveMechanism", type = DetectiveMechanismType.class),
        @XmlElement(name = "preventiveMechanism", type = PreventiveMechanismType.class)
    })
    protected List<MechanismBaseType> detectiveMechanismOrPreventiveMechanism;

    /**
     * Gets the value of the interfaceDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceDescriptionType }
     *     
     */
    public InterfaceDescriptionType getInterfaceDescriptions() {
        return interfaceDescriptions;
    }

    /**
     * Sets the value of the interfaceDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceDescriptionType }
     *     
     */
    public void setInterfaceDescriptions(InterfaceDescriptionType value) {
        this.interfaceDescriptions = value;
    }

    /**
     * Gets the value of the actionDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionDescriptionStoreType }
     *     
     */
    public ActionDescriptionStoreType getActionDescriptions() {
        return actionDescriptions;
    }

    /**
     * Sets the value of the actionDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionDescriptionStoreType }
     *     
     */
    public void setActionDescriptions(ActionDescriptionStoreType value) {
        this.actionDescriptions = value;
    }

    /**
     * Gets the value of the contextDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link ContextDescriptionType }
     *     
     */
    public ContextDescriptionType getContextDescriptions() {
        return contextDescriptions;
    }

    /**
     * Sets the value of the contextDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextDescriptionType }
     *     
     */
    public void setContextDescriptions(ContextDescriptionType value) {
        this.contextDescriptions = value;
    }

    /**
     * Gets the value of the detectiveMechanismOrPreventiveMechanism property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detectiveMechanismOrPreventiveMechanism property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetectiveMechanismOrPreventiveMechanism().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetectiveMechanismType }
     * {@link PreventiveMechanismType }
     * 
     * 
     */
    public List<MechanismBaseType> getDetectiveMechanismOrPreventiveMechanism() {
        if (detectiveMechanismOrPreventiveMechanism == null) {
            detectiveMechanismOrPreventiveMechanism = new ArrayList<MechanismBaseType>();
        }
        return this.detectiveMechanismOrPreventiveMechanism;
    }

}
