# libraries/thread/SConscript
import os, sys
Import('env','curBaseDir')

threadObject=env.rdObject('threadUtils.c', ccflags = env['CCFLAGS']+'-fno-builtin ')
env.rdAlias('pefThreadUtils', threadObject)

env.rdAlias('thread', threadObject)




