# libraries/action/SConscript
import os
Import('env','curBaseDir')

actionObject=env.rdObject('action.c')
env.rdAlias('action', actionObject)

paramObject=env.rdObject('paramDesc.c')
env.rdAlias('action', paramObject)

actionDescriptionStoreObject=env.rdObject('actionDescStore.c')
env.rdAlias('action', actionDescriptionStoreObject)



