package de.tum.in.i22.uc.cm.pip.interfaces;

public enum EScopeType {
	UNKNOWN, SAVE_FILE, LOAD_FILE, COPY_CLIPBOARD, PASTE_CLIPBOARD, SEND_SOCKET, READ_SOCKET, SEND_EMAIL, GET_EMAIL, JBC_GENERIC_LOAD, JBC_GENERIC_SAVE, BIN_GENERIC_LOAD, BIN_GENERIC_SAVE
}
