# libraries/logger/SConscript
import os
Import('env','curBaseDir')

loggerConfig=env.pefLoggerConfig(os.path.join(env['PEFBUILD'], "include", "logger_base.h"), 'logger.c')
Depends(loggerConfig, env['userConfFile'])
env.rdAlias('pefLoggerConfig', loggerConfig)

if env['android']==True:
  env.rdAlias('logger', [loggerConfig])
  Return()

loggerObject = env.Object('logger.c', CCFLAGS=env['CCFLAGS']+' -fno-builtin -O2 ')
loggerInternalObject = env.Object('logInternal.c', CCFLAGS=env['CCFLAGS']+' -fno-builtin -O2 ')
env.rdAlias('logger', [loggerObject, loggerInternalObject])
