# libraries/event/SConscript
import os
Import('env','curBaseDir')

pefEventObject = env.rdObject('pefEvent.c')
pefParamObject = env.rdObject('pefParam.c')
pefEventMatchObject = env.rdObject('pefEventMatch.c')
pefParamMatchObject = env.rdObject('pefParamMatch.c')

env.rdAlias('event', [pefEventMatchObject, pefEventObject, pefParamObject, pefParamMatchObject])

