//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:09:43 PM CEST 
//


package de.tum.in.i22.uc.ptp.ecajaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for InterfaceInstanceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InterfaceInstanceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="native"/>
 *     &lt;enumeration value="jni"/>
 *     &lt;enumeration value="socket"/>
 *     &lt;enumeration value="xmlrpc"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum InterfaceInstanceType {

    @XmlEnumValue("native")
    NATIVE("native"),
    @XmlEnumValue("jni")
    JNI("jni"),
    @XmlEnumValue("socket")
    SOCKET("socket"),
    @XmlEnumValue("xmlrpc")
    XMLRPC("xmlrpc");
    private final String value;

    InterfaceInstanceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterfaceInstanceType fromValue(String v) {
        for (InterfaceInstanceType c: InterfaceInstanceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
