//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:09:43 PM CEST 
//


package de.tum.in.i22.uc.ptp.ecajaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Interfaces for PEPs and PXPs, e.g. for action subscription or executors.
 * 
 * <p>Java class for InterfaceDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterfaceDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pep" type="{http://www.iese.fhg.de/pef/1.0/enforcementLanguage}InterfaceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pxp" type="{http://www.iese.fhg.de/pef/1.0/enforcementLanguage}InterfaceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterfaceDescriptionType", propOrder = {
    "pep",
    "pxp"
})
public class InterfaceDescriptionType {

    protected List<InterfaceType> pep;
    protected List<InterfaceType> pxp;

    /**
     * Gets the value of the pep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceType }
     * 
     * 
     */
    public List<InterfaceType> getPep() {
        if (pep == null) {
            pep = new ArrayList<InterfaceType>();
        }
        return this.pep;
    }

    /**
     * Gets the value of the pxp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pxp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPxp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceType }
     * 
     * 
     */
    public List<InterfaceType> getPxp() {
        if (pxp == null) {
            pxp = new ArrayList<InterfaceType>();
        }
        return this.pxp;
    }

}
