//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:09:43 PM CEST 
//


package de.tum.in.i22.uc.ptp.ecajaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateBasedOperatorType")
public class StateBasedOperatorType implements IOperatorType{

    @XmlAttribute
    protected String operator;

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    
    
    @XmlAttribute
    protected String param1;

    /**
     * Gets the value of the param1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam1() {
        return param1;
    }

    /**
     * Sets the value of the param1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam1(String value) {
        this.param1 = value;
    }
    
    
    @XmlAttribute
    protected String param2;

    /**
     * Gets the value of the param2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam2() {
        return param2;
    }

    /**
     * Sets the value of the param2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam2(String value) {
        this.param2 = value;
    }
    
    
    
    
    @XmlAttribute
    protected String param3;

    /**
     * Gets the value of the param3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParam3() {
        return param3;
    }

    /**
     * Sets the value of the param3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParam3(String value) {
        this.param1 = value;
    }
    
    
   
	@Override
	public OperatorTypeValue tellOperatorType() {
		
		return OperatorTypeValue.STATEBASED;
	}

	@Override
	public void configureMyself(String xmlNodeName, Object parent) {
		connectToMyParent(parent);
	}

	@Override
	public void connectToMyParent(Object parent) {
		
		if(parent!=null){
			if(parent instanceof UnaryOperatorType){
				UnaryOperatorType uotParent=(UnaryOperatorType) parent;
				uotParent.setStateBasedFormula(this);
			}
			else if(parent instanceof BinaryOperatorType){
				BinaryOperatorType botParent=(BinaryOperatorType) parent;
				ObjectFactory fact=new ObjectFactory();
				JAXBElement<StateBasedOperatorType> el=null;
				el=fact.createBinaryOperatorTypeStateBasedFormula(this);
				if(el!=null) 
					botParent.getOperatorsGroup().add(el);
			}
			else if(parent instanceof TimeBoundedUnaryOperatorType)
			{
				TimeBoundedUnaryOperatorType tParent = (TimeBoundedUnaryOperatorType) parent;
				tParent.setStateBasedFormula(this);
			}		
	  }
	}
	
	/**
	 * In trying to prepare condition from a state formula, we need to
	 * get the data attribute and the content of the state formula. This
	 * routine does just that.
	 * 
	 * @param node
	 */
	public void populateWithData(Node node){
		if(node!=null){
			//prepare data attribute
			String sOperator="";
			String sParam1="";
			String sParam2="";
			String sParam3="";
			if(node.getAttributes().getLength()>0){
				NamedNodeMap attributes = node.getAttributes();
				Node nOperator=attributes.getNamedItem("operator");
				Node nParam1 = attributes.getNamedItem("param1");
				Node nParam2 = attributes.getNamedItem("param2");
				Node nParam3 = attributes.getNamedItem("param3");
				if(nOperator!=null){
					sOperator=nOperator.getNodeValue();
					setOperator(sOperator);
				}
				if(nParam1!=null){
					sParam1=nParam1.getNodeValue();
					setParam1(sParam1);
				}
				if(nParam2!=null){
					sParam2=nParam2.getNodeValue();
					setParam2(sParam2);
				}
				if(nParam3!=null){
					sParam3=nParam3.getNodeValue();
					setParam3(sParam3);
				}
			}			
						
		}
	}

}
