//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.23 at 08:45:21 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iese.fhg.de/pef/1.0/enforcementLanguage", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tum.in.i22.uc.pmp.xsd;
